### ISSUE TITLE
v 1.4.0 nothing when creating task

### ISSUE THREAD

**Issue by jhekasoft** [QTodoTxt/QTodoTxt#168]
We have incorrect month number date.today().month+1. Because current month is 12. 12+1=13.

Traceback (most recent call last):
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/tasks_list_controller.py", line 142, in createTask
    (text, ok) = self._task_editor_service.createTask()
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/services/task_editor_service.py", line 42, in createTask
    (text, ok) = self._openTaskEditor("Create Task")
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/services/task_editor_service.py", line 51, in _openTaskEditor
    dialog = AutoCompleteInputDialog(uniqlist, self._parent_window)
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controls/autocomplete_inputdialog.py", line 17, in __init__
    self._populateKeys(self.autocomplete_pairs)
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controls/autocomplete_inputdialog.py", line 23, in _populateKeys
    EOM = 'due:' + (date.today().replace(month=date.today().month+1, day=1) - timedelta(days=1)).strftime('%Y-%m-%d')
ValueError: month must be in 1..12

**Comment by kmicc** [comment]
Thanks for reporting. Please see #166 and #164. Fixed in https://github.com/sdenel/QTodoTxt/commits/patch-1 or https://github.com/kmicc/QTodoTxt, but not yet merged into the master repository.

**Comment by jhekasoft** [comment]
Thank you. Sorry for duplicate issue.

**Comment by kmicc** [comment]
Closed by #164.
