### ISSUE TITLE
List of dependencies

### ISSUE THREAD

**Issue by alexkutsan** [QTodoTxt/QTodoTxt#265]
Probably it would be useful to create list of depencenciews for building and running QTodoTxt.
Because I just wanede to install it via pip and get an error:
```
➜  ~ pip install qtodotxt 
Collecting qtodotxt
  Downloading qtodotxt-1.6.1.tar.gz (95kB)
    100% |████████████████████████████████| 102kB 398kB/s 
Installing collected packages: qtodotxt
  Running setup.py install for qtodotxt ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8fxmew6v/qtodotxt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-q6thtr9o-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'depends'
      warnings.warn(msg)
...
➜  ~ qtodotxt 
Traceback (most recent call last):
  File "/usr/bin/qtodotxt", line 9, in <module>
    load_entry_point('qtodotxt==1.6.1', 'console_scripts', 'qtodotxt')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/qtodotxt/app.py", line 8, in <module>
    from PyQt5 import QtCore
ImportError: No module named 'PyQt5'

```

**Comment by oroulet** [comment]
dependencies are specified in setup.py file. It might be that pyqt5 is omitted to avoid triggering unwanted compiling. This might be wrong and you are welcome to add it and send a patch if you thing it is more correct

**Comment by oroulet** [comment]
but you should really consider installing pyqt5 using your os packages and not pip :-)
