### ISSUE TITLE
Exceptions/abort while entering regexp on search box

### ISSUE THREAD

**Issue by ehabkost** [QTodoTxt/QTodoTxt#276]
Running v1.6.2 directly from git clone.

Steps to reproduce:

1) Open `qtodotxt` in a terminal
2) Type `^[` on the search box
3) See the following on the terminal:

    $ qtodotxt
    Traceback (most recent call last):
      File "/home/ehabkost/system/soft/QTodoTxt/bin/../qtodotxt/lib/filters.py", line 372, in isMatch
        mymatch = re.search(restring, task.text, re.I | re.U)
      File "/usr/lib64/python3.5/re.py", line 173, in search
        return _compile(pattern, flags).search(string)
      File "/usr/lib64/python3.5/re.py", line 293, in _compile
        p = sre_compile.compile(pattern, flags)
      File "/usr/lib64/python3.5/sre_compile.py", line 536, in compile
        p = sre_parse.parse(p, flags)
      File "/usr/lib64/python3.5/sre_parse.py", line 829, in parse
        p = _parse_sub(source, pattern, 0)
      File "/usr/lib64/python3.5/sre_parse.py", line 437, in _parse_sub
        itemsappend(_parse(source, state))
      File "/usr/lib64/python3.5/sre_parse.py", line 545, in _parse
        source.tell() - here)
    sre_constants.error: unterminated character set at position 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ehabkost/system/soft/QTodoTxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 225, in _onSearchTextChanged
        self._applyFilters(searchText=searchText)
      File "/home/ehabkost/system/soft/QTodoTxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 211, in _applyFilters
        tasks = tasklib.filterTasks([SimpleTextFilter(searchText)], tasks)
      File "/home/ehabkost/system/soft/QTodoTxt/bin/../qtodotxt/lib/tasklib.py", line 190, in filterTasks
        if myfilter.isMatch(task):
      File "/home/ehabkost/system/soft/QTodoTxt/bin/../qtodotxt/lib/filters.py", line 378, in isMatch
        mymatch = re.search(restring3, task.text, re.I | re.U)
      File "/usr/lib64/python3.5/re.py", line 173, in search
        return _compile(pattern, flags).search(string)
      File "/usr/lib64/python3.5/re.py", line 293, in _compile
        p = sre_compile.compile(pattern, flags)
      File "/usr/lib64/python3.5/sre_compile.py", line 536, in compile
        p = sre_parse.parse(p, flags)
      File "/usr/lib64/python3.5/sre_parse.py", line 829, in parse
        p = _parse_sub(source, pattern, 0)
      File "/usr/lib64/python3.5/sre_parse.py", line 437, in _parse_sub
        itemsappend(_parse(source, state))
      File "/usr/lib64/python3.5/sre_parse.py", line 545, in _parse
        source.tell() - here)
    sre_constants.error: unterminated character set at position 1
    
4) Even after the exception, qtodotxt is still running
5) Continue typing in the search box (e.g. type `a`)
6) See qtodotxt abort:

```
Traceback (most recent call last):
  File "/home/ehabkost/system/soft/QTodoTxt/bin/../qtodotxt/lib/filters.py", line 371, in isMatch
    raise re.error('')  # otherwise adding closing parenth avoids error here
sre_constants.error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ehabkost/system/soft/QTodoTxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 225, in _onSearchTextChanged
    self._applyFilters(searchText=searchText)
  File "/home/ehabkost/system/soft/QTodoTxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 211, in _applyFilters
    tasks = tasklib.filterTasks([SimpleTextFilter(searchText)], tasks)
  File "/home/ehabkost/system/soft/QTodoTxt/bin/../qtodotxt/lib/tasklib.py", line 190, in filterTasks
    if myfilter.isMatch(task):
  File "/home/ehabkost/system/soft/QTodoTxt/bin/../qtodotxt/lib/filters.py", line 378, in isMatch
    mymatch = re.search(restring3, task.text, re.I | re.U)
  File "/usr/lib64/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib64/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib64/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib64/python3.5/sre_parse.py", line 545, in _parse
    source.tell() - here)
sre_constants.error: unterminated character set at position 1
Aborted (core dumped)

```

Additional info: running Fedora 24, python3-3.5.1-13.fc24.x86_64, python3-qt5-5.6-4.fc24.x86_64.

**Comment by PKEv** [comment]
closed via #288
