### ISSUE TITLE
beta version upload broken!!

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt#360]
I uploaded a beta version to pip but it does not run!!!

/usr/local/bin/qtodotxt 
Traceback (most recent call last):
  File "/usr/local/bin/qtodotxt", line 11, in <module>
    load_entry_point('qtodotxt==1.7.0b1', 'console_scripts', 'qtodotxt')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2268, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/qtodotxt/app.py", line 13, in <module>
    import pyqt5_style_rc  # noqa: F401
ImportError: No module named 'pyqt5_style_rc'

@PKEv you added dependency on files in root directory that should not be there! You need to move that kind of files to the qtodotxt directory, maybe a subdirectory under. as you want

**Comment by PKEv** [comment]
Where they need to move?

**Comment by PKEv** [comment]
please try: https://github.com/PKEv/QTodoTxt/tree/move_res

**Comment by oroulet** [comment]
looks good.

**Comment by oroulet** [comment]
ok now
