### ISSUE TITLE
Can anyone improve the instructions to running latest version on macOS?

### ISSUE THREAD

**Issue by forbesguthrie** [QTodoTxt/QTodoTxt#397]
The latest binary package for macOS is v1.4 which is about 2.5 years old.

*Has anyone gotten v1.7 to run on macOS yet?*

I have looked at the [building binary instructions](https://github.com/QTodoTxt/QTodoTxt/wiki/Building-QTodoTxt-Binaries) but failed to make progress myself.

https://github.com/QTodoTxt/QTodoTxt#running-from-sources explains that to run this on Windows/Linux/Mac you must install the [prerequisites](https://github.com/QTodoTxt/QTodoTxt/wiki), but this page only describes how to do this on Windows/Linux, not on a Mac.

Ideally someone could create a new updated binary, but in the interim is anyone able to improve the prereq instructions for MacOS?

([enhancement #118](https://github.com/QTodoTxt/QTodoTxt/issues/118) would be even better, but baby steps first I guess)

Appreciate any feedback on this. Thanks

**Comment by oroulet** [comment]
As far as I know none of the current developers use Mac. But help is
welcome.

**Comment by PKEv** [comment]
To begin, start with this:
https://www.python.org/downloads/mac-osx/
https://gist.github.com/guillaumevincent/10983814
after: google.com
during the occurrence of questions, please contact

**Comment by phargogh** [comment]
Hey everyone,

I can't claim to be a developer, but I have been using the last several releases of qtodotxt (including 1.7.0 at the moment) on my mac (yosemite, 10.10.5) without issue.  Instead of building a binary and building that, I just install via pip and launch the app via the commandline like so:

`$ python3 -c "import qtodotxt.app as app; app.run()`

I realize it's maybe not as ideal as a brew cask, but it does make upgrading as simple as `pip install --upgrade qtodotxt`.

**Comment by PKEv** [comment]
Could you write a little instruction for future generations?

**Comment by phargogh** [comment]
Of course!  And @forbesguthrie, I only just realized that your question had more to do with the prerequisites than actually launching the application. So sorry for the confusion!  I just updated the [prerequisite installation page on the wiki](https://github.com/QTodoTxt/QTodoTxt/wiki) to include two possible workflows for installing the beast that is PyQt5.  Personally, I'd recommend the homebrew route, as it sounds like you might already have `brew` installed on your system.

Hope this helps ... let me know if I can clarify anything!

**Comment by forbesguthrie** [comment]
Thanks @phargogh! I can run the latest qtodotxt now.

BTW, I added a line to your prereqs (xcode-select --install) for those that don't have it yet.

After using [pip to install qtodotxt](https://github.com/QTodoTxt/QTodoTxt#latest-stable-release) (pip install qtodotxt --upgrade) I still couldn't run it:
`Traceback (most recent call last):
  File "/usr/local/bin/qtodotxt", line 7, in <module>
    from qtodotxt.app import run
  File "/Library/Python/2.7/site-packages/qtodotxt/app.py", line 9, in <module>
    from PyQt5 import QtCore, QtGui
ImportError: No module named PyQt5`

But I was able to run it from the [source package](https://github.com/QTodoTxt/QTodoTxt#running-from-sources) okay.

**Comment by phargogh** [comment]
Ah, interesting!  It looks like the failed launch was running qtodotxt with python 2.7 ... the homebrew instructions on the wiki page only build the bindings for python 3.  I don't know myself if qtodotxt will run on python 2.7, honestly, but here's how you could install PyQt5 on python 2.7 via homebrew:

    brew unlink pyqt5
    brew install pyqt5 --with-python

To run qtodotxt from the command-line, you could uninstall qtodotxt and then reinstall it with pip3:

    pip uninstall qtodotxt
    pip3 install qtodotxt

This way, the qtodotxt will reference the python3 interpreter.

@PKEv, I see that the trove classifiers in `setup.py` state that the project is python3-only, but do you know if qtodotxt will run on python 2.7?

**Comment by oroulet** [comment]
For the entire time I have been involved the project has been python 3 only, so there are probably many python 3 specific things
