### ISSUE TITLE
QTodoTxt 1.6.1 doesn't start in Ubuntu 14.04 

### ISSUE THREAD

**Issue by winhex** [QTodoTxt/QTodoTxt#399]
QTodoTxt 1.6.1 doesn't start in Ubuntu 14.04 with the following error:

> 

Traceback (most recent call last):
  File "/usr/bin/qtodotxt", line 11, in <module>
    from qtodotxt import app
  File "/usr/share/qtodotxt/bin/../qtodotxt/app.py", line 13, in <module>
    from qtodotxt.ui.dialogs.taskeditor import TaskEditor
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/dialogs/taskeditor.py", line 2, in <module>
    from qtodotxt.ui.dialogs.taskeditor_dialog import TaskEditorDialog
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/dialogs/taskeditor_dialog.py", line 7, in <module>
    from dateutil.relativedelta import relativedelta
ImportError: No module named 'dateutil'

> 

I installed python-dateutil, but the problem has not been solved. After that I have the same error.

**Comment by oroulet** [comment]
Python3-dateutil

**Comment by winhex** [comment]
Thanks for the quick response, the problem is solved. It may be worth adding this dependency to deb-package?

**Comment by oroulet** [comment]
I think it is already added to git master. Maybe it is released in 1.7.0
