### ISSUE TITLE
Version 1.7.0 on Windows 10, won't start again

### ISSUE THREAD

**Issue by mummariello** [QTodoTxt/QTodoTxt#430]
After having modified option: "don't show completed tasks", qtodotxt won't start again.

stderr.log file showing this:
Traceback (most recent call last):
  File "qtodotxt.pyw", line 30, in <module>
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt\qtodotxt\app.py", line 146, in run
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt\qtodotxt\app.py", line 96, in _createController
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt\qtodotxt\ui\controllers\main_controller.py", line 40, in __init__
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt\qtodotxt\ui\controllers\main_controller.py", line 58, in _initControllers
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt\qtodotxt\ui\controllers\main_controller.py", line 262, in _initTasksList
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt\qtodotxt\ui\controllers\tasks_list_controller.py", line 39, in __init__
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt\qtodotxt\ui\controllers\tasks_list_controller.py", line 252, in disableTaskActions
AttributeError: 'TasksListController' object has no attribute 'deleteSelectedTasksAction'

Before this issue, it worked perfectly. I was not able to reset to start configuration, and so to run. I'm not an expert, i don't know how to do. I tried to install winpython, but nothing. same error.
I loved this software so much having tried many others, in many system of task managing. Using with Syncthing way to sync besides 2 pc and android. Wonderful. And qtodotxt is far the best managing crossplatform software of todo.txt file. i would not give up to use it. 
thank you for any help
Luigi

**Comment by mummariello** [comment]
solved cancelling config in qsetting system registry voice, as indicated in this page: http://doc.qt.io/qt-5/qsettings.html

**Comment by SaraMati** [comment]
I have the same issue, I reinstalled the app but it's not solved. how was it solved for you ultimately?
