### ISSUE TITLE
qtodotxt_1.6.1_all.deb on Kubuntu 17.10: the software can't launch

### ISSUE THREAD

**Issue by Deevad** [QTodoTxt/QTodoTxt#442]
Hi, 
I grabbed qtodotxt_1.6.1_all.deb after recommendation in the documentation (README.md) for my ubuntu based system (Kubuntu 17.10). After installing the software, I have the launcher in my menu. But if I press the launcher: I get a desktop notification the software crashed in background and nothing launch. Here is the terminal output if I launch it from command line:

```
 ~ »»» qtodotxt 
Traceback (most recent call last):
  File "/usr/bin/qtodotxt", line 11, in <module>
    from qtodotxt import app
  File "/usr/share/qtodotxt/bin/../qtodotxt/app.py", line 13, in <module>
    from qtodotxt.ui.dialogs.taskeditor import TaskEditor
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/dialogs/taskeditor.py", line 2, in <module>
    from qtodotxt.ui.dialogs.taskeditor_dialog import TaskEditorDialog
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/dialogs/taskeditor_dialog.py", line 7, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'
```

You can workaround by installing manually in command line :
```
sudo apt install python3-dateutil
```
Can you edit the 'control' plain text into the deb and add 'python3-dateutil' to the 'Depends' line ? Thank you!

**Comment by Knysliux001** [comment]
python3-dateutil should be marked as dependency for .deb package. It is not installed by default in Ubuntu 18.04 LTS

**Comment by Deevad** [comment]
@Knysliux001 , it was added 2 years ago https://github.com/QTodoTxt/QTodoTxt/commit/5d9d2452d806f4f04016fd48fe3dd9b477d9ef98 

The problem is we are using 1.6.1 version because no newer version are packaged as *.deb. ( ref: https://github.com/QTodoTxt/QTodoTxt/releases )
